requires 'Template';
requires 'File::Slurper';
requires 'File::Basename';
requires 'File::Copy';
requires 'Digest::MD5::File';
requires 'Digest::CRC';
requires 'Getopt::Long';
requires 'List::Compare';
requires 'TeX::Hyphen';
